Deviseによるログイン機能を追加
pepabo-college/dp42-todo-app pull request #4
Opened 2017-06-06 08:24 UTC by dp42

##　概要
Deviseを利用したログイン機能を実装しました。

## 確認いただきたいところ
下記ページのインストラクションを参考に実装したのですが、
設定漏れやおかしな記述がないかご確認いただきたいです。
http://guides.railsgirls.com/devise
https://github.com/plataformatec/devise

## レビュアー
@udzura @bake0937 @sunecosuri (敬称略)

2017-06-06 08:29 UTC, udzura requested changes

2017-06-06 08:29 UTC, udzura commented on test/models/user_test.rb
> +end
テストとしてはRSpecを利用する予定でした...
RSpecの規約に沿った空のファイルに変更していただけますか

2017-06-06 08:29 UTC, udzura commented on config/initializers/devise.rb
> +  # config.secret_key = '70a024116b12746c82c32d6481a2614dd93da6848cfaf43d5d538e637eadcc0f7e27bbdad67d17e1d31f002362247bd5e31356ddc4a7228ac0b515f3d5a8fd6a'
* この、secret_keyや、下にある `pepper` はコメントインしなくて大丈夫ですか？
* そもそも、これらはどういう用途のものでしょう？

2017-06-06 08:29 UTC, udzura commented on config/initializers/devise.rb
> +  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
ここは変えなくて大丈夫ですか？

2017-06-06 08:29 UTC, udzura commented on app/views/tasks/index.html.erb
> +<h4><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></h4>
LOGOUTボタンは、 `Tasks#index` に **だけ** 表示されていればOKでしょうか？
もっと適切な箇所はないだろうか？

2017-06-06 08:29 UTC, udzura commented on app/models/user.rb
> +         :recoverable, :rememberable, :trackable, :validatable
ここで宣言している devise のそれぞれのオプションは、どういう意味を持っていますか？

2017-06-06 08:48 UTC, dp42 commented on app/views/tasks/index.html.erb
> +<h4><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></h4>
ご指摘の通り全部のページでログアウト出来たほうが良いと思いましたので、
フッターにログアウトボタンを移動し、全てのページで表示されるように変更しました。

2017-06-06 08:52 UTC, dp42 commented on test/models/user_test.rb
> +end
インストール時に自動で作成されるデータをそのままにしてしまっていました。
RSpec形式のファイル名に変更して一旦空で保存しました。

2017-06-06 08:59 UTC, udzura commented on app/views/tasks/index.html.erb
> +<h4><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></h4>
💯

2017-06-06 09:01 UTC, udzura commented on test/models/user_test.rb
> +end
残念、ディレクトリ名が違います...

https://github.com/pepabo-college/dp42-todo-app/pull/4/commits/c9f28bead8097df3bcd2dc2c66c75b8b868bcd40

* https://github.com/rspec/rspec-rails#installation に沿ってrspec-railsのセットアップをする
* 空の `models/user_spec.rb` を配置する

までこのPRでやっちゃいましょうか

2017-06-07 00:52 UTC, bake0937 commented
Viewの修正をするプルリクの内容にスクリーンショットを載せるとレビュアーはレビューがやりやすくなることを思い出しました。
(私も今プルリク修正しました。)

2017-06-07 01:24 UTC, dp42 commented on config/initializers/devise.rb
> +  # config.secret_key = '70a024116b12746c82c32d6481a2614dd93da6848cfaf43d5d538e637eadcc0f7e27bbdad67d17e1d31f002362247bd5e31356ddc4a7228ac0b515f3d5a8fd6a'
- secret_key
  - Deviseがトークンの生成のために使う秘密鍵。
  - デフォルトではsecret_key_baseの値が利用される。
  - developmentおよびtest環境についてはconfig/secret.ymlに直接記述されている。
  - production環境では環境変数を参照するようになっている。
  - config.secret_keyをコメント飲するとその値が利用される。

production環境の秘密鍵をgit管理しているファイルに直接記述することはセキュリティによろしくないでは？と考えました。
そのためsecret_keyはコメントアウトしたままにしておき、本番環境で環境変数を設定したいと思います。

- pepper
  - パスワードを暗号化する際にパスワードに付加する文字列
  - pepperを有効にしていなければ設定不要

今回はpepperを利用しない設定なのでコメントアウトの状態で問題ないと考えます。

2017-06-07 01:28 UTC, dp42 commented on config/initializers/devise.rb
> +  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
実際のメール送信者のメールアドレスが記載されているべきなので修正いたします。
今回は自身のメールアドレスを設定します。

2017-06-07 02:01 UTC, dp42 commented on app/models/user.rb
> +         :recoverable, :rememberable, :trackable, :validatable
宣言することでdeviseのモジュールが有効になります。
それぞれの機能は以下の通りです。

- :database_authenticatable
ログインを試みるユーザーを認証するためにパスワードの暗号化およびDBへの保存を行う機能。

- :registerable
アカウントの新規登録や削除の機能

- :recoverable
パスワードをリセットし、再設定手順をユーザーに送る機能

- :rememberable
クッキーを利用してログイン状態を保持する機能

- :trackable
ログイン回数、ログイン時刻、接続元IPアドレスを記録する機能

- :validatable
入力されたメールアドレスとパスワードのバリデーションを行う機能

2017-06-07 02:06 UTC, dp42 commented on test/models/user_test.rb
> +end
承知いたしました。

2017-06-07 05:32 UTC, udzura commented on config/initializers/devise.rb
> +  # config.secret_key = '70a024116b12746c82c32d6481a2614dd93da6848cfaf43d5d538e637eadcc0f7e27bbdad67d17e1d31f002362247bd5e31356ddc4a7228ac0b515f3d5a8fd6a'
💯

2017-06-07 05:35 UTC, udzura approved these changes

2017-06-07 05:35 UTC, merged